/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contacorrente;

import javax.swing.JOptionPane;

/**
 *
 * @author salmo
 */
public class JFrameDeposito extends javax.swing.JFrame {
    Conta c1;
    ContaPoupanca c2;
    ContaEspecial c3;
    /**
     * Creates new form JFrameDeposito
     * @param c1
     * @param c2
     * @param c3
     */
    public JFrameDeposito(Conta c1, ContaPoupanca c2, ContaEspecial c3) {
        this.c1=c1;
        this.c2=c2;
        this.c3=c3;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        buttonMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textConta = new javax.swing.JTextField();
        textValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setText("Deposito:");

        buttonOk.setText("Ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonMenu.setText("Menu");
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Nº da conta:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Valor R$:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(buttonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMenu)
                    .addComponent(buttonOk))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        JFrameInicio inicio = new JFrameInicio(this.c1,this.c2,this.c3);
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_buttonMenuActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
        int flag;
        
        if( Integer.parseInt(textConta.getText()) == c1.getNumero() ){
            flag = JOptionPane.showConfirmDialog(null, c1.getNome() + ",você confirma essa operação ?","Deposito",JOptionPane.OK_CANCEL_OPTION);
            
            if(flag == JOptionPane.OK_OPTION){
                c1.depositar(Double.parseDouble(textValor.getText()));
                JOptionPane.showMessageDialog(null, "Depósito efetuado com sucesso!","Desposito",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                inicio.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Operação cancelada.","Deposito",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                inicio.setVisible(true);
            }
        }else
        if( Integer.parseInt(textConta.getText()) == c2.getNumero() ){
            flag = JOptionPane.showConfirmDialog(null, c2.getNome() + ",você confirma essa operação ?","Deposito",JOptionPane.OK_CANCEL_OPTION);

            if(flag == JOptionPane.OK_OPTION){
                c2.depositar(Double.parseDouble(textValor.getText()));
                JOptionPane.showMessageDialog(null, "Depósito efetuado com sucesso!","Desposito",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                inicio.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Operação cancelada.","Deposito",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                inicio.setVisible(true);
            }
        }else
        if( Integer.parseInt(textConta.getText()) == c3.getNumero() ){
            flag = JOptionPane.showConfirmDialog(null, c3.getNome() + ",você confirma essa operação ?","Deposito",JOptionPane.OK_CANCEL_OPTION);
               
            if(flag == JOptionPane.OK_OPTION){
                   c3.depositar(Double.parseDouble(textValor.getText()));
                   JOptionPane.showMessageDialog(null, "Depósito efetuado com sucesso!","Desposito",JOptionPane.INFORMATION_MESSAGE);
                   this.setVisible(false);
                   inicio.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Operação cancelada.","Deposito",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                inicio.setVisible(true);
                   
            }
               
        }else{
            JOptionPane.showMessageDialog(null,"Número da conta inválido.","Warning",JOptionPane.WARNING_MESSAGE); 
        }    
    }//GEN-LAST:event_buttonOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMenu;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textConta;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
