/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contacorrente;

import javax.swing.JOptionPane;

/**
 *
 * @author salmo
 */
public class JFrameTransferencia extends javax.swing.JFrame {
    Conta c1;
    ContaPoupanca c2;
    ContaEspecial c3;
    /**
     * Creates new form JFrameTransferencia
     * @param c1
     * @param c2
     * @param c3
     */
    public JFrameTransferencia(Conta c1, ContaPoupanca c2, ContaEspecial c3) {
        this.c1=c1;
        this.c2=c2;
        this.c3=c3;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textDConta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textPConta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textDValor = new javax.swing.JTextField();
        buttonMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setText("Transferência:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("De:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Para:");

        buttonOk.setText("Ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel5.setText("Nº da conta:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel6.setText("Nº da conta:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel7.setText("Valor R$:");

        buttonMenu.setText("Menu");
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPConta))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDValor)
                            .addComponent(textDConta))))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMenu)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textDConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textDValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textPConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk)
                    .addComponent(buttonMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        if( (Integer.parseInt(textDConta.getText()) == c1.getNumero()) && (Integer.parseInt(textPConta.getText()) == c2.getNumero()) ){
           JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
           int flag;
           
           flag = JOptionPane.showConfirmDialog(null, c1.getNome() + ",você gostaria de transferir R$" + Double.parseDouble(textDValor.getText()) + " para " + c2.getNome()+" ?","Transferencia",JOptionPane.OK_CANCEL_OPTION);
           
           if(flag == JOptionPane.OK_OPTION){
               
               c1.sacar(Double.parseDouble(textDValor.getText()));
               c2.depositar(Double.parseDouble(textDValor.getText()));
               JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null,"Operação cancelada.","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
           }
        }else
        if( (Integer.parseInt(textDConta.getText()) == c1.getNumero()) && (Integer.parseInt(textPConta.getText()) == c3.getNumero()) ){
            JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
            int flag;
           
            flag = JOptionPane.showConfirmDialog(null, c1.getNome() + ",você gostaria de transferir R$" + Double.parseDouble(textDValor.getText()) + " para " + c3.getNome()+" ?","Transferencia",JOptionPane.OK_CANCEL_OPTION);
           
            if(flag == JOptionPane.OK_OPTION){
               
               c1.sacar(Double.parseDouble(textDValor.getText()));
               c3.depositar(Double.parseDouble(textDValor.getText()));
               JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null,"Operação cancelada.","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }
        }else
        if( (Integer.parseInt(textDConta.getText()) == c2.getNumero()) && (Integer.parseInt(textPConta.getText()) == c1.getNumero()) ){
            JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
            int flag;
           
            flag = JOptionPane.showConfirmDialog(null, c2.getNome() + ",você gostaria de transferir R$" + Double.parseDouble(textDValor.getText()) + " para " + c1.getNome()+" ?","Transferencia",JOptionPane.OK_CANCEL_OPTION);
           
            if(flag == JOptionPane.OK_OPTION){
               
               c2.sacar(Double.parseDouble(textDValor.getText()));
               c1.depositar(Double.parseDouble(textDValor.getText()));
               JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null,"Operação cancelada.","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }
        }else
        if( (Integer.parseInt(textDConta.getText()) == c2.getNumero()) && (Integer.parseInt(textPConta.getText()) == c3.getNumero()) ){
            JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
            int flag;
           
            flag = JOptionPane.showConfirmDialog(null, c2.getNome() + ",você gostaria de transferir R$" + Double.parseDouble(textDValor.getText()) + " para " + c3.getNome()+" ?","Transferencia",JOptionPane.OK_CANCEL_OPTION);
           
            if(flag == JOptionPane.OK_OPTION){
               
               c2.sacar(Double.parseDouble(textDValor.getText()));
               c3.depositar(Double.parseDouble(textDValor.getText()));
               JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null,"Operação cancelada.","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }
        }else
        if( (Integer.parseInt(textDConta.getText()) == c3.getNumero()) && (Integer.parseInt(textPConta.getText()) == c1.getNumero()) ){
            JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
            int flag;
           
            flag = JOptionPane.showConfirmDialog(null, c3.getNome() + ",você gostaria de transferir R$" + Double.parseDouble(textDValor.getText()) + " para " + c1.getNome()+" ?","Transferencia",JOptionPane.OK_CANCEL_OPTION);
           
            if(flag == JOptionPane.OK_OPTION){
               
               c3.sacar(Double.parseDouble(textDValor.getText()));
               c1.depositar(Double.parseDouble(textDValor.getText()));
               JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null,"Operação cancelada.","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }
        }else
        if( (Integer.parseInt(textDConta.getText()) == c3.getNumero()) && (Integer.parseInt(textPConta.getText()) == c2.getNumero()) ){
            JFrameInicio inicio = new JFrameInicio(this.c1, this.c2, this.c3);
            int flag;
           
            flag = JOptionPane.showConfirmDialog(null, c3.getNome() + ",você gostaria de transferir R$" + Double.parseDouble(textDValor.getText()) + " para " + c2.getNome()+" ?","Transferencia",JOptionPane.OK_CANCEL_OPTION);
           
            if(flag == JOptionPane.OK_OPTION){
               
               c3.sacar(Double.parseDouble(textDValor.getText()));
               c2.depositar(Double.parseDouble(textDValor.getText()));
               JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }else{
               JOptionPane.showMessageDialog(null,"Operação cancelada.","Transferencia",JOptionPane.INFORMATION_MESSAGE);
               this.setVisible(false);
               inicio.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Número das contas inválido.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        JFrameInicio inicio = new JFrameInicio(this.c1,this.c2,this.c3);
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_buttonMenuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMenu;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textDConta;
    private javax.swing.JTextField textDValor;
    private javax.swing.JTextField textPConta;
    // End of variables declaration//GEN-END:variables
}
